# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'stravels' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stravels
  pod 'MobileCenter/Push', '~> 0.12.1'
  pod 'MobileCenter/Crashes', '~> 0.12.1'
  pod 'MobileCenter/Analytics', '~> 0.12.1'
  pod 'RNMobileCenterShared', '~> 0.9.0'

end
